about/urls.py
from django.urls import path
from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    ]

posts/urls.py
from django.urls import path

from .views import *

app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('group/<slug:slug>/', group_posts, name='group_post'),
    path('profile/<str:username>/', profile, name='profile'),
    path('posts/<int:post_id>/', post_detail, name='post_detail'),
    path('create/', post_create, name='post_create'),
    path('<int:pk>/edit/', PostEdit.as_view(), name='edit'),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    group = models.ForeignKey(
        'Group',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='Группа',
    )

    def __str__(self):
        return self.text[:15]

    def get_absolute_url(self):
        return f'/posts/{self.pk}/'


class Group(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

posts/forms.py
from django.forms import ModelForm

from .models import Post


class CreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']

    def __init__(self, *args, **kwargs):
        super(CreateForm, self).__init__(*args, **kwargs)
        self.fields['group'].empty_label = None
        #following line needed to refresh widget copy of choice list
        self.fields['group'].widget.choices = self.fields['group'].choices

posts/views.py
import self as self
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from .models import Post, Group
from .forms import CreateForm

def authorized_only(func):
    # Функция-обёртка в декораторе может быть названа как угодно
    def check_user(request, *args, **kwargs):
        # В любую view-функцию первым аргументом передаётся объект request,
        # в котором есть булева переменная is_authenticated,
        # определяющая, авторизован ли пользователь.
        if request.user.is_authenticated:
            # Возвращает view-функцию, если пользователь авторизован.
            return func(request, *args, **kwargs)
        # Если пользователь не авторизован — отправим его на страницу логина.
        return redirect('/auth/login/')
    return check_user


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    # Если порядок сортировки определен в классе Meta модели,
    # запрос будет выглядеть так:
    # post_list = Post.objects.all()
    # Показывать по 10 записей на странице.
    paginator = Paginator(post_list, 10)

    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get('page')

    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)

    # Отдаем в словаре контекста
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.all().filter(group=group).order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post = post_list.first()
    context = {
        'group': group,
        'page_obj': page_obj,
        'post': post,
    }
    return render(request, 'posts/group_list.html', context=context)

def profile(request, username):
    posts = Post.objects.filter(author__username=username).order_by('-pub_date')
    post_count = posts.count()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post = posts.first()
    context = {
        'page_obj': page_obj,
        'count': post_count,
        'post': post,
    }
    return render(request, 'posts/profile.html', context=context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    posts = Post.objects.filter(author__username=post.author.username).count()
    context = {
        'post': post,
        'posts': posts,
    }
    return render(request, 'posts/post_detail.html', context=context)

@authorized_only
def post_create(request):
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('posts:index')
    else:
        form = CreateForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context=context)

class PostEdit(UpdateView):
    model = Post
    template_name = 'posts/create.html'
    form_class = CreateForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise Http404("You are not allowed to edit this Post")
        return super(PostEdit, self).dispatch(request, *args, **kwargs)

templates/posts/create.html
{% extends 'base.html' %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Новый пост
              </div>
              <div class="card-body">
                <form method="post" action="">
                    {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger" >*</span>
                    </label>
                    {{form.text}}
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа
                    </label>
                    <select id="id_group" style="padding-left:0px;padding-right:0px">
                      {% for group in form.group %}
                      <option>{{group}}</option>>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    {% with request.resolver_match.view_name as view_name %}
                    {% if view_name == 'posts:edit' %}
                    <button type="submit" class="btn btn-primary">
                      Сохранить
                    </button>
                    {% else %}
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                    {% endif %}
                    {% endwith %}
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/posts/group_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-5">
<h1>Записи сообщества: {{ post.group }}</h1>
{% for post in page_obj %}
  <ul>
    <li>
       Автор: {{ post.author.get_full_name }}  <a href="{% url 'posts:profile' post.author %}">все записи пользователя</a>
    </li>
    <li>
       Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  <p><a href="{% url 'posts:index' %}">все записи сообщества</a></p>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
</div>>
{% endblock %}

templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

{% for post in page_obj %}
  <ul>
    <li>
       Автор: {{ post.author.get_full_name }}
    </li>
    <li>
       Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% if post.group %}
    <a href="{% url 'posts:group_post' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html'  %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->
            <li class="list-group-item">
              {% if post.group %}
              Группа: {{ post.group }}
              <a href="{% url 'posts:group_post' post.group.slug %}">все записи группы</a>
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  {{ posts }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           {{ post.text }}
          </p>
          {% if request.user == post.author%}
        <a class="btn btn-primary" href="{% url 'posts:edit' post.pk %}">
              редактировать запись
            </a>
          {% endif %}
        </article>
      </div>
    {% endblock %}

templates/posts/profile.html
{% extends 'base.html'  %}
{% block content %}
      <div class="container py-5">
        <h1>Все посты пользователя: {{ post.author.get_full_name }} </h1>
        <h3>Всего постов: {{ count }} </h3>
        <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
          {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.pk %}"> Подробная информация </a>
        {% if post.group %}
          <p><a href="{% url 'posts:group_post' post.group.slug %}">все записи группы</a></p>
        {% endif %}
        </article>
        <hr>
      </div>
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}