about/urls.py
from django.urls import path
from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    ]

posts/urls.py
from django.urls import path

from .views import *

app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('group/<slug:slug>/', group_posts, name='group_post'),
    path('profile/<str:username>/', profile, name='profile'),
    path('posts/<int:post_id>/', post_detail, name='post_detail'),
    path('create/', post_create, name='post_create'),
    path('<int:pk>/edit/', PostEdit.as_view(), name='edit'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        views.MyPasswordChangeView.as_view(),
        name='change_password'

    ),
    path(
        'password_change/done/',
        views.MyPasswordResetDoneView.as_view(),
        name='change_password_done'
    ),
    path(
        'password_reset/',
        views.MyPasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.MyPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        views.MyPasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
    path(
        'password_reset/done/',
        views.MyPasswordResetEmailDoneView.as_view(),
        name='password_done'
    )

]

templates/includes/footer.html
<footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
    </footer>

templates/includes/header.html
<header>
    {% load static %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {# Добавлено в спринте #}

      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов
      {% endcomment %}
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:author' %} active {% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %} active {% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:post_create' %} active {% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:change_password' %} active {% endif %}" href="{% url 'users:change_password' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:login' %} active {% endif %}" href= "{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {# Конец добавленого в спринте #}
    </div>
  </nav>
  {% endwith %}
</header>